steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build data container image'
    args: [
      'build',
      '.',
      '-t',
      'europe-west1-docker.pkg.dev/mlops-hatespeech/hs-images/bert-app',
      '-f',
      'dockerfiles/app.dockerfile'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push data container image'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/mlops-hatespeech/hs-images/bert-app'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args: [
      'run',
      'deploy',
      'bert-app',
      '--image',
      'europe-west1-docker.pkg.dev/mlops-hatespeech/hs-images/bert-app',
      '--region',
      'europe-west1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--memory',
      '1Gi',
      '--timeout',
      '300'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
