data_path: "data/processed"
baseOutputDirectory:
  outputUriPrefix: gs://mlops_hs_data_europe_west1/logs/
workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
      imageUri: europe-west1-docker.pkg.dev/mlops-hatespeech/hs-images/train-image:latest
      command:
        - bash
        - -c
        - python src/mlops_hatespeech/data.py && python src/mlops_hatespeech/train.py
hyperparameters:
    lr: 2.0e-5
    wd: 1e-3
    epochs: 5
    seed: 42
    per_device_train_batch_size: 32
    per_gpu_eval_batch_size: 128
    gradient_accumulation_steps: 2
    logging_strategy: "steps"
    logging_steps: 100
    save_strategy: "epoch"
    eval_strategy: "steps"
    eval_steps: 100
    save_total_limit: 1
    use_cpu: true
    load_best_model_at_end: false
    report_to: "wandb"
    dataloader_num_workers: 0
