serviceAccount: train-vm-sa@mlops-hatespeech.iam.gserviceaccount.com

workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
      imageUri: europe-west1-docker.pkg.dev/mlops-hatespeech/hs-images/train-image
      command:
        - bash
      args:
        - -c
        - |
          dvc pull data/processed.dvc && \
          python -u src/mlops_hatespeech/train.py --epochs 2 && \
          dvc add logs/run1 && \
          dvc push
      env:
        - name: WANDB_API_KEY
          value: "c2f58591ace6d74472c0cc8e17533a4d893477a1"
