steps:
  - name: "alpine"
    id: "Replace values in the training config"
    entrypoint: "sh"
    args:
      - '-c'
      - |
        apk add --no-cache gettext
        envsubst < vertex_config_train.yaml > vertex_config_train.yaml.tmp
        mv vertex_config_train.yaml.tmp vertex_config_train.yaml
    secretEnv: ['WANDB_API_KEY']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Train on vertex AI'
    waitFor: ['Replace values in the training config']
    args: [
      'ai',
      'custom-jobs',
      'create',
      '--region',
      'europe-west1',
      '--display-name',
      'train-job',
      '--config',
      '${_VERTEX_TRAIN_CONFIG}',
    ]

substitutions:
  _VERTEX_TRAIN_CONFIG: 'vertex_config_train.yaml'

availableSecrets:
  secretManager:
    - versionName: projects/178847025464/secrets/WANDB_API_KEY/versions/1
      env: 'WANDB_API_KEY'
