serviceAccount: train-vm-sa@mlops-hatespeech.iam.gserviceaccount.com
workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
      imageUri: europe-west1-docker.pkg.dev/mlops-hatespeech/hs-images/evaluate
      command:
        - bash
      args:
        - -c
        - |
          dvc pull data/processed.dvc && \
          python src/mlops_hatespeech/evaluate.py