program: src/mlops_hatespeech/train.py
name: sweepdemo
project: mlops_hatespeech
entity: soenia-ludwig-maximilianuniversity-of-munich
method: random
metric:
    goal: minimize
    name: eval/loss
parameters:
    lr:
        distribution: log_uniform_values
        min: 0.0001
        max: 0.1
    epochs:
        values: [5, 10, 15]
run_cap: 10
