name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    - name: Set PYTHONPATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Set PYTHONPATH (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $current = $Env:PYTHONPATH
        $new = "$current;${PWD}\src"
        echo "PYTHONPATH=$new" >> $Env:GITHUB_ENV

    - name: Login to W&B
      run: wandb login ${{ secrets.WANDB_API_KEY }}

    - name: Write GCP key JSON file and set GOOGLE_APPLICATION_CREDENTIALS (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      env:
        GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}
      run: |
        echo "$GCP_KEY_JSON" > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV

    - name: Write GCP key JSON file and set GOOGLE_APPLICATION_CREDENTIALS (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}
      run: |
        $path = "$PWD\gcp-key.json"
        Set-Content -Path $path -Value $Env:GCP_KEY_JSON -Encoding utf8
        echo "GOOGLE_APPLICATION_CREDENTIALS=$path" >> $Env:GITHUB_ENV

    - name: Run tests with coverage
      run: |
        coverage run --source=src/mlops_hatespeech -m pytest -v
        coverage report
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
